name: Deploy Vite React App

on:
  push:
    branches:
      - main  
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  

    - name: Install dependencies for 05passwordgenerator
      run: |
        cd react/05passwordgenerator  # Navigate into your specific project directory
        npm install  # Install the dependencies for this project

    - name: Build the project
      run: |
        cd react/05passwordgenerator  # Navigate again to the correct folder
        npm run build  # Run the build script for this specific project

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./react/05passwordgenerator/dist  
